import { columns } from '@/components/columns';
import { DataTable } from '@/components/data-table';

// Delete this component
function getData() {
    // Simulate fetching data from an API
    return Promise.resolve([
        {
            id: '1',
            assetTag: 'PPO-LV-01',
            vehicleName: 'Toyota Hi-ace',
            model: 'Toyota',
            type: 'Van',
            capacity: 12,
            location: 'PPO Garage',
            yearAcquired: 2019,
            category: 'Light Vehicle',
            plateNumber: 'ABC123',
            meterReading: 23476,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '2',
            assetTag: 'PPO-SD-02',
            vehicleName: 'Honda City',
            model: 'Honda',
            type: 'Sedan',
            capacity: 5,
            location: 'PPO Parking Lot',
            yearAcquired: 2021,
            category: 'Light Vehicle',
            plateNumber: 'DEF456',
            meterReading: 18765,
            fuelType: 'Gasoline',
            status: 'Operational',
        },
        {
            id: '3',
            assetTag: 'PPO-VN-03',
            vehicleName: 'Nissan NV350',
            model: 'Nissan',
            type: 'Van',
            capacity: 15,
            location: 'PPO Garage',
            yearAcquired: 2020,
            category: 'Light Vehicle',
            plateNumber: 'GHI789',
            meterReading: 29834,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '4',
            assetTag: 'PPO-BS-04',
            vehicleName: 'Hino RK1J',
            model: 'Hino',
            type: 'Bus',
            capacity: 45,
            location: 'PPO Bus Depot',
            yearAcquired: 2018,
            category: 'Heavy Vehicle',
            plateNumber: 'JKL012',
            meterReading: 89234,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '5',
            assetTag: 'PPO-SD-05',
            vehicleName: 'Toyota Vios',
            model: 'Toyota',
            type: 'Sedan',
            capacity: 5,
            location: 'PPO Parking Lot',
            yearAcquired: 2022,
            category: 'Light Vehicle',
            plateNumber: 'MNO345',
            meterReading: 7462,
            fuelType: 'Gasoline',
            status: 'Operational',
        },
        {
            id: '6',
            assetTag: 'PPO-VN-06',
            vehicleName: 'Ford Transit',
            model: 'Ford',
            type: 'Van',
            capacity: 12,
            location: 'PPO Garage',
            yearAcquired: 2019,
            category: 'Light Vehicle',
            plateNumber: 'PQR678',
            meterReading: 32145,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '7',
            assetTag: 'PPO-TR-07',
            vehicleName: 'Isuzu F-Series',
            model: 'Isuzu',
            type: 'Truck',
            capacity: 3,
            location: 'PPO Warehouse',
            yearAcquired: 2017,
            category: 'Heavy Vehicle',
            plateNumber: 'STU901',
            meterReading: 105432,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '8',
            assetTag: 'PPO-MC-08',
            vehicleName: 'Yamaha NMAX',
            model: 'Yamaha',
            type: 'Motorcycle',
            capacity: 2,
            location: 'PPO Parking Shed',
            yearAcquired: 2023,
            category: 'Light Vehicle',
            plateNumber: 'VWX234',
            meterReading: 1324,
            fuelType: 'Gasoline',
            status: 'Operational',
        },
        {
            id: '9',
            assetTag: 'PPO-BS-09',
            vehicleName: 'Fuso Rosa',
            model: 'Fuso',
            type: 'Bus',
            capacity: 30,
            location: 'PPO Bus Depot',
            yearAcquired: 2016,
            category: 'Heavy Vehicle',
            plateNumber: 'YZA567',
            meterReading: 120894,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '10',
            assetTag: 'PPO-TR-10',
            vehicleName: 'Mitsubishi Fuso Canter',
            model: 'Mitsubishi',
            type: 'Truck',
            capacity: 6,
            location: 'PPO Warehouse',
            yearAcquired: 2015,
            category: 'Heavy Vehicle',
            plateNumber: 'BCD890',
            meterReading: 145678,
            fuelType: 'Diesel',
            status: 'Out of service',
        },
        {
            id: '11',
            assetTag: 'PPO-VN-11',
            vehicleName: 'Hyundai Staria',
            model: 'Hyundai',
            type: 'Van',
            capacity: 11,
            location: 'PPO Garage',
            yearAcquired: 2022,
            category: 'Light Vehicle',
            plateNumber: 'EFG123',
            meterReading: 9643,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '12',
            assetTag: 'PPO-SD-12',
            vehicleName: 'Mazda 3',
            model: 'Mazda',
            type: 'Sedan',
            capacity: 5,
            location: 'PPO Parking Lot',
            yearAcquired: 2023,
            category: 'Light Vehicle',
            plateNumber: 'HIJ456',
            meterReading: 3120,
            fuelType: 'Gasoline',
            status: 'Operational',
        },
        {
            id: '13',
            assetTag: 'PPO-BS-13',
            vehicleName: 'Isuzu LT134P',
            model: 'Isuzu',
            type: 'Bus',
            capacity: 50,
            location: 'PPO Bus Depot',
            yearAcquired: 2017,
            category: 'Heavy Vehicle',
            plateNumber: 'KLM789',
            meterReading: 135678,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '14',
            assetTag: 'PPO-MC-14',
            vehicleName: 'Honda Click',
            model: 'Honda',
            type: 'Motorcycle',
            capacity: 2,
            location: 'PPO Parking Shed',
            yearAcquired: 2021,
            category: 'Light Vehicle',
            plateNumber: 'NOP012',
            meterReading: 7856,
            fuelType: 'Gasoline',
            status: 'Operational',
        },
        {
            id: '15',
            assetTag: 'PPO-TR-15',
            vehicleName: 'Hino 500',
            model: 'Hino',
            type: 'Truck',
            capacity: 5,
            location: 'PPO Warehouse',
            yearAcquired: 2018,
            category: 'Heavy Vehicle',
            plateNumber: 'QRS345',
            meterReading: 125436,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '16',
            assetTag: 'PPO-VN-16',
            vehicleName: 'Chevrolet Express',
            model: 'Chevrolet',
            type: 'Van',
            capacity: 10,
            location: 'PPO Garage',
            yearAcquired: 2020,
            category: 'Light Vehicle',
            plateNumber: 'TUV678',
            meterReading: 28456,
            fuelType: 'Diesel',
            status: 'Operational',
        },
        {
            id: '17',
            assetTag: 'PPO-SD-17',
            vehicleName: 'Hyundai Accent',
            model: 'Hyundai',
            type: 'Sedan',
            capacity: 5,
            location: 'PPO Parking Lot',
            yearAcquired: 2021,
            category: 'Light Vehicle',
            plateNumber: 'WXY901',
            meterReading: 14532,
            fuelType: 'Gasoline',
            status: 'Operational',
        },
        // Add more sample data as needed
    ]);
}

export function VehicleTable({ vehicles }) {
    // const [data, setData] = React.useState([]);

    // React.useEffect(() => {
    //   async function fetchData() {
    //     const result = await getData();
    //     setData(result);
    //   }
    //   fetchData();
    // }, []);

    return (
        <div className="container mx-auto">
            <DataTable columns={columns} data={vehicles} />
        </div>
    );
}
